name: build extension

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: use node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - run: npm install
 
    - run: npm run build --if-present

    - run: npm run compile --if-present
    
    # todo fix x server dependencies for vscode tests to execute
    - run: echo "npm test"

  # lint:
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #   - uses: actions/checkout@v4
  #
  #   - name: use node.js 20.x
  #     uses: actions/setup-node@v4
  #     with:
  #       node-version: 20.x
  #       cache: 'npm'
  #  
  #   - run: npm install
  #    
  #   - run: npm run lint
